<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Content\Images\abacoicon.gif" />
    <None Remove="Content\Images\Calendario.gif" />
    <None Remove="Content\Images\contacto.png" />
    <None Remove="Content\Images\Flashicon.gif" />
    <None Remove="Content\Images\icon-abacus.png" />
    <None Remove="Content\Images\icon-brain.png" />
    <None Remove="Content\Images\icon-finger.png" />
    <None Remove="Content\Images\iconoMM.png" />
    <None Remove="Content\Images\im1bg.png" />
    <None Remove="Content\Images\im2.png" />
    <None Remove="Content\Images\mano-derecha.png" />
    <None Remove="Content\Images\mano-izquierda.png" />
    <None Remove="Content\Images\ManosF.gif" />
    <None Remove="Content\Images\MMlogo.png" />
    <None Remove="Content\Images\multicon.png" />
    <None Remove="Content\Images\Nosotros1.png" />
    <None Remove="Content\Images\Nosotros2.png" />
    <None Remove="Content\Images\Nosotros3.png" />
    <None Remove="Content\Images\ProfS.png" />
    <None Remove="Content\Images\SRicon.gif" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Content\Images\abacoicon.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Calendario.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\contacto.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Flashicon.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\icon-abacus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\icon-brain.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\icon-finger.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\iconoMM.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\im1bg.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\im2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\mano-derecha.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\mano-izquierda.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ManosF.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\MMlogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\multicon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Nosotros1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Nosotros2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Nosotros3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ProfS.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\SRicon.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataBase\DataBase.csproj" />
  </ItemGroup>

</Project>
