<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Content\Images\0.png" />
    <None Remove="Content\Images\1.png" />
    <None Remove="Content\Images\2.png" />
    <None Remove="Content\Images\3.png" />
    <None Remove="Content\Images\4.png" />
    <None Remove="Content\Images\5.png" />
    <None Remove="Content\Images\6.png" />
    <None Remove="Content\Images\7.png" />
    <None Remove="Content\Images\8.png" />
    <None Remove="Content\Images\9.png" />
    <None Remove="Content\Images\abacoicon.gif" />
    <None Remove="Content\Images\brain.gif" />
    <None Remove="Content\Images\Calendario.gif" />
    <None Remove="Content\Images\contacto.png" />
    <None Remove="Content\Images\dados.gif" />
    <None Remove="Content\Images\Dados\dado1.png" />
    <None Remove="Content\Images\Dados\dado2.png" />
    <None Remove="Content\Images\Dados\dado3.png" />
    <None Remove="Content\Images\Dados\dado4.png" />
    <None Remove="Content\Images\Dados\dado5.png" />
    <None Remove="Content\Images\Dados\dado6.png" />
    <None Remove="Content\Images\Dados\Demogorgon.png" />
    <None Remove="Content\Images\division.gif" />
    <None Remove="Content\Images\Flashicon.gif" />
    <None Remove="Content\Images\icon-abacus.png" />
    <None Remove="Content\Images\icon-brain.png" />
    <None Remove="Content\Images\icon-finger.png" />
    <None Remove="Content\Images\iconoMM.png" />
    <None Remove="Content\Images\im1bg.png" />
    <None Remove="Content\Images\im2.png" />
    <None Remove="Content\Images\ListaBasica\10.png" />
    <None Remove="Content\Images\ListaBasica\11.png" />
    <None Remove="Content\Images\ListaBasica\12.png" />
    <None Remove="Content\Images\ListaBasica\13.png" />
    <None Remove="Content\Images\ListaBasica\14.png" />
    <None Remove="Content\Images\ListaBasica\15.png" />
    <None Remove="Content\Images\ListaBasica\16.png" />
    <None Remove="Content\Images\ListaBasica\17.png" />
    <None Remove="Content\Images\ListaBasica\18.png" />
    <None Remove="Content\Images\ListaBasica\19.png" />
    <None Remove="Content\Images\ListaBasica\2.png" />
    <None Remove="Content\Images\ListaBasica\20.png" />
    <None Remove="Content\Images\ListaBasica\4.png" />
    <None Remove="Content\Images\ListaBasica\5.png" />
    <None Remove="Content\Images\ListaBasica\6.png" />
    <None Remove="Content\Images\ListaBasica\7.png" />
    <None Remove="Content\Images\ListaBasica\8.png" />
    <None Remove="Content\Images\ListaBasica\9.png" />
    <None Remove="Content\Images\logosr.png" />
    <None Remove="Content\Images\ManosF.gif" />
    <None Remove="Content\Images\memorias.gif" />
    <None Remove="Content\Images\MMLogo.png" />
    <None Remove="Content\Images\multicon.png" />
    <None Remove="Content\Images\multip.gif" />
    <None Remove="Content\Images\Nosotros1.png" />
    <None Remove="Content\Images\Nosotros2.png" />
    <None Remove="Content\Images\Nosotros3.png" />
    <None Remove="Content\Images\parejas.gif" />
    <None Remove="Content\Images\ProfS.png" />
    <None Remove="Content\Images\póker.gif" />
    <None Remove="Content\Images\raices.gif" />
    <None Remove="Content\Images\SRicon.gif" />
    <None Remove="Content\Images\SRlottie.gif" />
    <None Remove="Content\Images\ViajeAmerica\1.png" />
    <None Remove="Content\Images\ViajeAmerica\10.png" />
    <None Remove="Content\Images\ViajeAmerica\11.png" />
    <None Remove="Content\Images\ViajeAmerica\12.png" />
    <None Remove="Content\Images\ViajeAmerica\13.png" />
    <None Remove="Content\Images\ViajeAmerica\14.png" />
    <None Remove="Content\Images\ViajeAmerica\15.png" />
    <None Remove="Content\Images\ViajeAmerica\16.png" />
    <None Remove="Content\Images\ViajeAmerica\17.png" />
    <None Remove="Content\Images\ViajeAmerica\18.png" />
    <None Remove="Content\Images\ViajeAmerica\19.png" />
    <None Remove="Content\Images\ViajeAmerica\2.png" />
    <None Remove="Content\Images\ViajeAmerica\20.png" />
    <None Remove="Content\Images\ViajeAmerica\3.png" />
    <None Remove="Content\Images\ViajeAmerica\4.png" />
    <None Remove="Content\Images\ViajeAmerica\5.png" />
    <None Remove="Content\Images\ViajeAmerica\6.png" />
    <None Remove="Content\Images\ViajeAmerica\7.png" />
    <None Remove="Content\Images\ViajeAmerica\8.png" />
    <None Remove="Content\Images\ViajeAmerica\9.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Content\Images\0.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\7.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\9.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\abacoicon.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\brain.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Calendario.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\contacto.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\dados.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\dado1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\dado2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\dado3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\dado4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\dado5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\dado6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Dados\Demogorgon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\division.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Flashicon.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\icon-abacus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\icon-brain.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\icon-finger.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\iconoMM.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\im1bg.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\im2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\10.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\11.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\12.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\13.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\14.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\15.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\17.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\18.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\19.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\20.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\7.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ListaBasica\9.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\logosr.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ManosF.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\memorias.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\MMLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\multicon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\multip.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Nosotros1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Nosotros2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\Nosotros3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\parejas.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ProfS.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\póker.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\raices.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\SRicon.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\SRlottie.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\10.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\11.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\12.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\13.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\14.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\15.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\17.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\18.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\19.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\20.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\7.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Content\Images\ViajeAmerica\9.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataBase\DataBase.csproj" />
  </ItemGroup>

</Project>
